### ISSUE TITLE
SyntaxError : Non ASCII character

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/snowsaw#20]
> This issue has been moved from arcticicestudio/igloo#20 reported by @teslaji

The exception is thrown by the non ASCII character `❄` [used in the `cli.py` log message](https://github.com/arcticicestudio/snowsaw/blob/develop/snowsaw/cli.py#L87).
Regarding to [PEP-263](https://www.python.org/dev/peps/pep-0263/) the default encoding is set to ASCII, but the file must be parsed as UTF-8.

This can be fixed by adding the magic comment `# -*- coding: utf-8 -*-`.

**Comment by arcticicestudio** [comment]
@teslaji You can checkout :seedling: [bugfix/gh-20-syntaxerror-non-ascii-character](https://github.com/arcticicestudio/snowsaw/tree/bugfix/gh-20-syntaxerror-non-ascii-character) to test if this fixes your problem.

**Comment by kbuley** [comment]
Same issue here, resolved by this fix

**Comment by arcticicestudio** [comment]
@kbuley Thanks for the feedback, already forgot to submit a PR for this one in the flood of issue notifications each day :smile: 

I'll add the magic comment to all other files to make sure the encoding is always UTF-8 and merge it as soon as possible.
