### ISSUE TITLE
Modify hosts to allow for 'default' 

### ISSUE THREAD

**Issue by kbuley** [arcticicestudio/snowsaw#21]
Currently there are two options regarding links and hosts. One is to have the link created on every machine, the other is to specifically call out machines. I propose adding the ability to set a default link so that if a host is named a specific file can be linked, otherwise a generic file can be used.

```json
"link": {
  "~/.gitconfig": {
    "create": true,
    "hosts": {
      "archlinux-home": "gitconfig.home",
      "archlinux-work": "gitconfig.work",
      "default": "gitconfig.generic"
    }
  }
}
```

**Comment by kbuley** [comment]
Submitted #22

**Comment by arcticicestudio** [comment]
Thanks for your contribution, this look like a nice feature :+1: 

I'll try to review and test it today.

**Comment by kbuley** [comment]
I've been using justone/dfm-site for a long time, but it just wasn't flexible enough to handle my work, which spans linux, osx, and windows (using babun) machines. I found snowsaw via dotbot and was amazed at how powerful it is, and simple at the same time. I'd love to have the same functionality for the shell plugin as well. I haven't looked at that code yet, but I might submit  either a PR or a new plugin. Love it!

**Comment by arcticicestudio** [comment]
Sorry for the delay, had no time during the week to review your PR. Feel free to submit a PR for the `shell` core plugin if, I'm happy for every contribution :smile:

**Comment by dhanyacp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
rslopes, @Catherine111ylq, @j-xor-l, @jurev, @Eivlys, @lowtrak, @shijunlin, @zhouop0, @YangHu-yh, @luowanglin, @Efrat19, @hahadaxia, @Cutler-Mamba, @azizahmed45, @HanYouyang, @oiserworld, @radamanthus, @CronusCipher, @jassak, @jw0903, @Alpha2J, @kuorus, @kamilbolka, @jasonraimondi, @JunoaJuno, @hauntingjungle5, @robot518, @KarateJB, @guyuedumingx, @CleitonAlmeida, @yikoujinxin, @Damn-It-Tech, @jmnsf, @KazumaTakata, @netherD, @CarrieKAI, @chyidl, @eloylp, @h4mit, @caixinning, @Lohann, @jozn, @omaragha98, @raymondmgeni, @Hitechmaroh, @modenaxe, @vagueanxiety, @sanghumchoi, @gokhanbaydar, @dbalikhinAdamMcIntosh, @oa1mgo, @yuxianggu, @keel1982, @yudikubota, @Shelday, @4B5F5F4B, @zyxzyxzyx, @BlankSeraph, @suleh, @DanaSandman, @srinivasank, @ArvinKing77, @banben, @ntn888, @RaoPrashanth, @bdougie, @wjamieson, @Royalsspirit, @p1kos, @asscarecrow, @MZawnings, @lyhourchhen, @WESapONE, @BigCatAccount, @zhanbei, @patrickxchong, @dpsahoo, @bashell, @flaviomori, @avinsit123, @isgo-golgo13, @alexmatthewfong, @ramigs, @wgrzr, @AmbiousXX, @JamesG419, @KhushJain, @cxphong, @camilo0365, @BhavyaSheth22, @nassu4, @klintcheng, @binghy, @Vicarious1, @gklo, @mark-chainalysis, @dieselkimeko, @donaldxdonald, @JoaoVLimashahedex, @knholland, @interstellar-hitchhiker, @vladozc, @tukwan, @psykclone, @jackblack369, @YinglunQ, @Amanshenoy008, @sauercrowd, @AntonioArts, @RJerry, @thoughtstirring, @0xfinegold, @colman62, @jatinmehrotra, @sarn1, @, @cmball1, @qbolgi, @ilovebenjamins, @harryluyah, @ginxzheng, @ecyuan, @chi11ed, @LINYINGXI90, @akolybelnikov, @maximsan, @merkle-groot, @cxmda, @ilijapet, @ZhaoHan7, @tong-xz, @hbccdf, @michealzh, @LEXSSAMA, @ATP4, @silencetwain, @IMARVI, @Cypert92, @qducnguyen, @minbyulcat, @gxh1124, @asmitbhantana, @matstam, @fkrieter, @rular099, @HobbyTransform, @AlanNggg, @wuxiangwatyphoonbb, @vxvaibhavxv, @xealml, @davidrmh, @tjourneyinge, @JustCallMe-AK, @minias, @Andoreatta, @debbieelo, @calidion, @mositori, @kustov-an, @dmascali, @user-name-is-taken, @prasannavl, @treystevens, @Trytan6bz, @onimz, @lndj, @jsander128, @nkabiru, @lionsole, @sexyberry, @darwindu, @0ximalice, @prokripto2135, @swiftguy52, @0xgxthxb, @Hrtypist, @Mcdulldog, @karl-p, @YswStudio, @vladkinoman, @cliangcliang, @hun5932, @KuanJiang2018, @vintidui, @sandybradley, @cheuk209, @therush77, @diegopastor, @bergusman, @gocdata, @handiko, @pshin45, @hungngk98, @7hny, @AkifhanIlgaz, @weaming, @Flowttersircatalyst, @he11bunny, @chandlerroth, @c0utin, @hood, @zszia, @mdiener21, @Lugitan, @Parklife05, @shuiniu86, @Nikita1710, @Pratik01-git, @flurbyjim, @soerenpriess, @KaKauff, @xuchongfeng, @DiHares, @CeramicDingo, @coderdung, @yezhenzhao, @ideaspad, @CHLK, @markoer73, @mccarthydanielle, @pengfeichen, @ProtonGustave, @kevindragon, @sigurdarson, @marsbible, @xuanboksnb, @amilube, @rafaelpardor, @vendci, @hasanfd, @jamesisaacs2, @2lim37, @austinvach, @jokergaming, @daniel-s-ingram, @Everhard, @heregoes, @maiduc22, @beeporb, @eurekawild, @spnraju, @naveenjohnsonv, @keclements, @hunterluker, @swanandmehta, @WalterSimoncinimipo915, @AliakseiPischyk, @bgpo, @Apollopog, @handflucht, @orchildsmall, @bhagyeshsoni98, @rd-sharma7, @AKJK-Internet-Megacorps, @pascArr, @2019-GitHub-Chu, @jiacai2050, @FaberSanZ, @Lock-And-Key, @nickfraser, @carrot369, @FR15, @kakirastern, @carly, @Yang-Thinker, @mindrunner, @adrian-kong, @bored17, @karna0730, @daesongE, @peiqc, @fieu, @iamNoah1, @tropology, @rajatkapoor, @devinbileck, @Niwilai, @dalaohekele, @sleepdrift3r, @cpt-waffle, @eler, @twofaktor, @tuanpht, @artelix01, @ebonie-l-l, @Jayjay1488, @AcquireKnown, @ashutoshkulks22, @MarkKobs, @arkodeep3404, @ItsMikeF, @KirillMoizik, @zhaomengru2015, @taoyafan, @Leonardofreua

**Comment by htsplex** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
alealmuna, @coodered, @tlylt, @ssv445, @wlb5396340, @michaelgbenle, @IvanovRoman, @AdamuAbba, @apekris, @pwqw, @maslovks2, @mrkskwsnck, @lucasninjaturtle, @beskay, @BlaM, @TTMARSH, @netherD, @svrnhdl, @mudbee111, @Houseplant1, @gabflima, @synvus, @tamobee, @RyotoSuzuki, @chrisxiao, @avikt18, @xuanhan863, @dmicc, @Xiaojs20, @pwws, @awtran, @ochebotar, @sleepy-mouse, @cezarypiatek, @reynlu, @Jaceyli, @vishwajeetkr, @guidenis93, @greenteafree, @MaevleKongen, @DelevoXDG, @pejaneczek, @lennyvong, @wesbmr2511, @dliu, @fahmiirsyadk, @kermitdafrog8, @chackerian, @afewnotes, @adamprescottlucas-quinn, @fatihardazengin, @atandrewtan, @chunngoo23, @getspooky, @herendian, @akinncar, @calvinrzachman, @chasel, @muratcankaracabey, @DejanMilicic, @cardosofede, @jacky2020hor, @haybb, @aiselo, @jaggedlittleredpill, @Not-Sarthak, @johnlaskowski, @MohammadAzimi, @MartinJaskulla, @intSpark, @EveDreamer, @ttiiggss, @Vskilet, @jayrmotta, @skeleton1231, @shauway, @yanyanhu, @this-vishalsingh, @pretzelpanda13, @xbotuk, @jofernandes, @rogertorres, @johntomczak, @MinhuiWan, @suvayu, @awmyhr, @Parasar, @saadazghour, @vvonchain, @MeABzZz, @xotonic, @vlasebian, @Albire001, @g10guang, @murka, @scriptzteam, @elfiii, @TimiBolu, @vincent131HarshSolanki18, @bohruz, @j-poneil, @caacuna, @brunoalano, @rrdesc, @rkalis, @kumicumz, @alex-arhat, @wonderzdh, @lidonghao1116, @HaydnHou, @Investman1, @linsanityHuang, @dislab-io, @Dadogg80, @ruchirpatel, @iamdbc, @wasphin, @manny-pi, @JonathanFu, @Rodeby, @learsu, @nanpuhaha, @rodnandes, @xiezhenye, @droidLight, @wedsonlima, @yzuyhp, @jjsub, @csy1204, @srkn, @marmelo-cotoneum, @Anomali007, @Felix-Hz, @winnerineast, @tiffany, @gtt116, @5mho, @HaosGames, @youngershen, @pmiklos, @aurelienmaurel, @amritanshu19, @manteih, @NawfalTachfine, @sfusato, @ABitCraft, @BlockFox, @kissartisanLock-And-Key, @massigarg, @netrazor, @Nalanae, @wayneyaoo, @junz83, @rench1988, @konalexiou, @xbbkok, @pietro-93, @penghaos, @oshliaer, @0xCFx, @sriharip316, @santhosh-kumar, @zhouhongjian, @erandakarachchi, @mariano-aguero, @bobieliu, @nodicora, @liuchuanbao, @Lzok, @rahul4k, @dahifi, @quietprofessor, @jaygidwitz, @vizanto, @ReinhardHsu, @PRKKILLER, @nerffei, @findingbugs, @larssonandreas, @kvthr, @dongsongliu, @handflucht, @zheng-ji, @dylnslck, @oa1mgo, @dodikk, @mboukhlouf, @lkfbr, @Borwe, @heyen-zxy, @Assios, @summerblue, @Rombusevil, @dotran, @gardoroman, @valcosmos, @fmirasnicolofarfante, @chaitanyaphalak, @curioustushar, @tenosh, @JMIdeaMaker, @mohammed-ali-1, @MYoshitake-1031, @chuongvhn, @usernamex, @michaelchiche, @gawrav, @Sohee-Kr, @javadosa, @SongChujun, @rogues-gallery, @Ayukha, @HashWarlock, @arthaszeng, @derek518, @yixxas, @solguatelli, @chuanski, @dhananjayd1729, @huynguyend191, @jney, @hector12free, @Adamu369, @refcell, @Mithileshraj123, @enming73, @metsch, @rmshea, @yubozhao, @franquis, @Huge, @terryjray, @falhad, @harikt, @fuyi501, @zan1105, @NikhilBagwe, @qiyeboy, @edno, @fzxu, @madztheo, @antlis, @DevdudeSami, @shark1976, @captainmike, @XWJACKtthwmk, @liubin18911671739, @wenyunxin, @etigerstudio, @Camps94, @TiO2, @emann-u-el, @GuadaGallardo, @miles170, @Ha4a4ck, @nichotined, @teddy3737, @alexbab90, @KevinBlandy, @AnubisZ2, @jbsmith86, @nagmnt, @Bulletninja, @codename12345, @akeemattelus, @weilongahut, @BenEdridge, @shoibalc, @sqwu, @DemmonChen, @7mue3ttT, @kayyp, @stevenkitter, @GBKader, @poundhu, @lxfind, @pradel, @jimmyhong94, @davechenww, @dekadentno, @donbing, @anishpateluk, @tatyana-hrusheva, @ericmm, @efrageek, @NemesisLW, @bieli, @callummole, @daryllxd, @Qubeo, @partyspy, @pavoltravnik, @pengkobe, @dosvidos, @Floernt
